language: node_js

node_js:
  - "6"

branches:
  only:
    - master

sudo: false

script:
  - npm run lint:fix
  - npm run test:cov

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run codecov

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
